name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/*.md'
      - '.github/workflows/**'  # Skip CD for workflow-only changes
      - 'LICENSE'
      - '.gitignore'
      - '.prettierignore'
      - '.eslintignore'
      - '.vscode/**'
      - '.editorconfig'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      # Auto-merge release PRs after checks pass
      - name: Enable auto-merge for release PR
        if: ${{ steps.release.outputs.pr }}
        run: |
          PR_JSON='${{ steps.release.outputs.pr }}'
          PR_NUMBER=$(echo "${PR_JSON}" | jq -r '.number')
          echo "Enabling auto-merge for PR #${PR_NUMBER}"
          gh pr merge "${PR_NUMBER}" --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

  build-and-upload:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test run

      - name: Build extension
        run: pnpm build

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r ../chrome-markdownify-v${{ needs.release-please.outputs.version }}.zip .
          cd ..

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: chrome-markdownify-v${{ needs.release-please.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}