name: CI

on:
  pull_request:
    branches: [main]  # CI runs only on PRs targeting main
  push:
    branches:
      - develop  # Optional: run CI on develop branch pushes
      - 'release-please--**'  # Run CI on release-please branches

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run type check
        run: pnpm tsc --noEmit

      - name: Run tests
        run: pnpm test run

      - name: Build extension (dry run)
        run: pnpm build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/manifest.json" ]; then
            echo "Build failed: manifest.json not found"
            exit 1
          fi
          echo "Build verification passed ✓"

      - name: Upload build artifacts (for PR review)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: pr-build-${{ github.event.pull_request.number }}
          path: dist/
          retention-days: 7